name: deploy the project to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dep
        run: pnpm i

      - name: Bundle project
        run: pnpm build

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: '${{ secrets.SERVER_PRIVATE_KEY }}'
          local_path: 'cloudshutter/dist/*'
          remote_path: '/Project/cloudshutter'
          args: '-o ConnectTimeout=5'
