name: deploy the project to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          user: root
          host: ${{ secrets.SERVER_IP }}
          pass: ${{secrets.PASSWORD}}
          port: 22
          connect_timeout: 10s
          first_ssh: |
            rm -rf ~/Project/cloudshutter
          scp: |
            './*' => ~/Project/cloudshutter/
      - name: restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            cd ~/Project/cloudshutter
            chomod +x deploy.sh
            bash deploy.sh
